/**
 * DEMO DATA — sample AI guidance plans.
 *
 * All guidance text below is SAMPLE CONTENT written to demonstrate the review
 * workflow. It is not generated by any AI model and is not official curriculum
 * guidance. The guidance engine will supply real plans later.
 */
import type { GuidancePlan, GuidanceStatus, GuidanceStep, Student } from '../types'
import { STUDENTS } from './students'
import { getClass } from './classes'

interface GuidanceTemplate {
  method: string
  rationale: string
  sequence: GuidanceStep[]
  pacing: string
  practice: string[]
  parentTip: string
  studentSequence: string[]
}

/** Sample templates keyed by demo competency name (Mathematics only in this prototype). */
const TEMPLATES: Record<string, GuidanceTemplate> = {
  'Ratio and Proportion': {
    method: 'Visual aids with worked examples',
    rationale:
      'Recent responses show the learner can compare two quantities but has difficulty writing the relationship as a ratio and scaling it. Visual grouping followed by worked examples builds the link step by step.',
    sequence: [
      { title: 'Revisit multiplication and division facts', detail: 'Short warm-up on the facts used when simplifying and scaling ratios.' },
      { title: 'Introduce ratio with visual groups', detail: 'Use drawn groups of objects to show “for every 2 of these, there are 3 of those”.' },
      { title: 'Write ratios in simplest form', detail: 'Worked examples moving from pictures to the a : b notation.' },
      { title: 'Equivalent ratios and scaling', detail: 'Use ratio tables to scale both parts by the same number.' },
      { title: 'Simple proportion word problems', detail: 'Apply ratios to everyday sharing and recipe problems.' },
    ],
    pacing: 'Three 40-minute lessons over one week, followed by a short check-in quiz.',
    practice: ['Understanding Ratios (10 questions)', 'Equivalent Ratios (8 questions)', 'Ratio Word Problems (6 questions)'],
    parentTip: 'Spend a few minutes practising simple ratio examples, such as sharing sweets or cups of water in a 2 to 1 pattern.',
    studentSequence: ['Understanding Ratios', 'Equivalent Ratios', 'Ratio Word Problems'],
  },
  Percentages: {
    method: 'Worked examples',
    rationale:
      'The learner converts simple fractions correctly but is less secure when finding a percentage of a quantity. Worked examples connect the two ideas.',
    sequence: [
      { title: 'Link fractions to percentages', detail: 'Show ½, ¼ and ¹⁄₁₀ as 50%, 25% and 10%.' },
      { title: 'Percentage of a quantity', detail: 'Worked examples using 10% as a building block.' },
      { title: 'Percentages in context', detail: 'Short problems on discounts and marks.' },
    ],
    pacing: 'Two 40-minute lessons, then practice during the following week.',
    practice: ['Fractions to Percentages (8 questions)', 'Finding a Percentage (8 questions)'],
    parentTip: 'When shopping or cooking, ask your child what half or a quarter of an amount is, and what that is as a percentage.',
    studentSequence: ['Fractions to Percentages', 'Finding a Percentage'],
  },
  Decimals: {
    method: 'Visual aids',
    rationale: 'Place value beyond the decimal point is not yet secure. Number lines and place-value charts make the positions visible.',
    sequence: [
      { title: 'Place value chart with tenths and hundredths', detail: 'Build numbers on a chart before writing them.' },
      { title: 'Decimals on a number line', detail: 'Order and compare decimals visually.' },
      { title: 'Adding and subtracting decimals', detail: 'Line up place values with worked examples.' },
    ],
    pacing: 'Two 40-minute lessons over one week.',
    practice: ['Decimal Place Value (10 questions)', 'Comparing Decimals (8 questions)'],
    parentTip: 'Look at prices together and talk about which is larger, for example 1.5 or 1.25.',
    studentSequence: ['Decimal Place Value', 'Comparing Decimals'],
  },
  Fractions: {
    method: 'Peer learning with visual aids',
    rationale: 'The learner recognises fractions but finds equivalent fractions harder. Paired work with fraction strips supports discussion.',
    sequence: [
      { title: 'Fraction strips', detail: 'Compare fraction lengths in pairs.' },
      { title: 'Equivalent fractions', detail: 'Find matching strips and record them.' },
      { title: 'Simplifying fractions', detail: 'Worked examples using common factors.' },
    ],
    pacing: 'Two 40-minute lessons in one week.',
    practice: ['Equivalent Fractions (8 questions)', 'Simplifying Fractions (8 questions)'],
    parentTip: 'Cut a chapati or piece of fruit into equal parts and talk about halves, quarters and eighths.',
    studentSequence: ['Equivalent Fractions', 'Simplifying Fractions'],
  },
  'Whole Numbers': {
    method: 'Worked examples',
    rationale: 'Errors cluster around place value in larger numbers. Step-by-step worked examples address this directly.',
    sequence: [
      { title: 'Place value in 4-digit numbers', detail: 'Expand numbers into thousands, hundreds, tens and ones.' },
      { title: 'Comparing and ordering', detail: 'Use place value to compare numbers.' },
    ],
    pacing: 'One to two 40-minute lessons.',
    practice: ['Place Value (10 questions)'],
    parentTip: 'Read large numbers together, such as prices or distances, and say what each digit is worth.',
    studentSequence: ['Place Value'],
  },
  Measurement: {
    method: 'Peer learning',
    rationale: 'Conversions between units are inconsistent. Measuring real objects in pairs gives concrete experience.',
    sequence: [
      { title: 'Measure classroom objects', detail: 'Pairs measure and record lengths in cm and m.' },
      { title: 'Converting units', detail: 'Worked examples for cm ↔ m and g ↔ kg.' },
    ],
    pacing: 'Two 40-minute lessons.',
    practice: ['Converting Units (8 questions)'],
    parentTip: 'Measure things at home together using a tape measure or a cup, and talk about the units.',
    studentSequence: ['Converting Units'],
  },
}

const STATUS_CYCLE: GuidanceStatus[] = ['pending_review', 'pending_review', 'approved', 'pending_review', 'revision_requested', 'approved', 'overridden']

function buildPlan(student: Student, index: number): GuidancePlan | null {
  const gap = student.currentFocus
  const t = TEMPLATES[gap]
  if (!t) return null
  const cls = getClass(student.classId)
  const status: GuidanceStatus = student.id === 's-001' ? 'pending_review' : STATUS_CYCLE[index % STATUS_CYCLE.length]!
  return {
    id: `gd-${student.id}`,
    studentId: student.id,
    subject: 'Mathematics',
    competencyGap: gap,
    curriculumReference: `Demo reference · ${cls?.level ?? ''} Mathematics · ${gap}`,
    createdOn: `2026-09-${String(24 - (index % 6)).padStart(2, '0')}`,
    status,
    teachingApproach: { method: t.method, rationale: t.rationale },
    sequence: t.sequence,
    pacing: t.pacing,
    practice: t.practice,
    outputs: {
      teacherSheet: `${t.method}. ${t.sequence.map((s, i) => `${i + 1}) ${s.title}`).join('; ')}. ${t.pacing}`,
      parentNote: t.parentTip,
      studentSequence: t.studentSequence,
    },
    teacherNote: status === 'overridden' ? 'Teacher chose to cover this in whole-class revision instead.' : undefined,
  }
}

/** Guidance plans exist for demo students with at least one area requiring support. */
export const GUIDANCE_PLANS: GuidancePlan[] = STUDENTS.filter((s) => s.needsSupport)
  .map((s, i) => buildPlan(s, i))
  .filter((p): p is GuidancePlan => p !== null)

export function getGuidance(id: string): GuidancePlan | undefined {
  return GUIDANCE_PLANS.find((g) => g.id === id)
}

export function getGuidanceForStudent(studentId: string): GuidancePlan | undefined {
  return GUIDANCE_PLANS.find((g) => g.studentId === studentId)
}

export function getGuidanceTemplate(competency: string) {
  return TEMPLATES[competency]
}

export const GUIDANCE_STATUS_LABEL: Record<GuidanceStatus, string> = {
  pending_review: 'Awaiting review',
  approved: 'Approved',
  revision_requested: 'Revision requested',
  overridden: 'Overridden',
}
